nelmio_api_doc:
    documentation:
        info:
            title: Mostar bus
            description: Mostar bus!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)